openapi: 3.0.0
info:
  title: IFC Call Quality API
  description: REST API for IFC Call Quality Project
  version: 1.0.0
components:
  schemas:
    LogError:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        stack:
          type: string
        timestamp:
          type: number
      required:
        - status
        - message
security:
  - bearerAuth: [ ]
paths:   
  /logerrors:
    post:
      description: Store a UI Logs information
      tags:
        - UIlogerror
      requestBody:
        description: requested LogError information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogError'
      responses:
        '200':
          description: Available Log error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Credentials:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Cache-Control:
              schema:
                type: string
                default: "no-cache,no-store,max-age=0,s-maxage=0,must-revalidate"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogError'
      x-amazon-apigateway-integration:
          uri: !Sub arn:aws:apigateway:ap-south-1:logs:action/PutLogEvents
          passthroughBehavior: when_no_match
          httpMethod: POST
          credentials: arn:aws:iam::761944119947:role/api_gateway_cloudwatch_global
          type: aws
          responses:
            default:
              statusCode: 200
              responseTemplates:
                application/json: '{"message": "success"}'
          requestParameters:
            integration.request.header.Content-Type: "'application/x-amz-json-1.1'"
            integration.request.header.X-Amz-Target: "'Logs_20140328.PutLogEvents'"
          requestTemplates:
            application/json: '{
                "logEvents": [
                    {
                      "message": $input.json("$.message"),
                      "timestamp": $input.json("$.timestamp")
                    }
                ],
                "logGroupName":  "/aws/ui/log-error",
                "logStreamName": "sample"
            }'
